# Site settings
title: Francis Shanahan
email: 
description: "http://LinkedIn.com/in/FrancisShanahan"
baseurl: ""
url: "http://FrancisShanahan.com"
twitter_username: FrancisShanahan
github_username:  FrancisShanahan

# Build settings
markdown: kramdown
permalink: pretty
